apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/service-upstream: "true"
  name: fan-out-ingress
  namespace: default
spec:
  ingressClassName: nginx 
  rules:
  - host: my-frontend-app.io
    http:
      paths:
      - path: /
        backend:
          service:
            name: my-frontend-app
            port:
              number: 80
        pathType: ImplementationSpecific
      # - path: /green
      #   backend:
      #     service:
      #       name: webserver-green-svc
      #       port:
      #         number: 80
      #   pathType: ImplementationSpecific